#!/usr/local/cpanel/3rdparty/bin/perl

print "Executing post-create script.. \n";

my %OPTS = @ARGV;

my %plans = (
				"shelltest",
				"shelltest2",
				"shelltest3"
			); # Array containing plans/packages that should have jailshell enabled.

my $user = $OPTS{'user'};
my $plan = $OPTS{'plan'};

print "Username: " . $user . "\n";
print "Plan: " . $plan . "\n";

for ( %plans ) {
	if ( $plan eq $_ )  {
		print "Jailshell Package Detected.. \n";
		exec "chsh -s /usr/local/cpanel/bin/jailshell $user" or print STDERR "Couldn't change shell: $!";
		last;
	}
}

