#!/usr/local/cpanel/3rdparty/bin/perl

print "Executing post-create script.. \n";

# Grab wwwacct arguments:
my %OPTS = @ARGV;

# Set the default path for reference file
my $base_path = "/etc/jailplans";

my @plans;

if (-e $base_path)  {
	@plans = do {
		open my $fh, "<", $base_path
			or die "Could not open $base_path: $!";
			<$fh>;
	};
	
	print join( ", ", @plans);
}

# Setup array containing plans/packages that should have jailshell enabled:
#my %plans = (
#				"shelltest",
#				"shelltest2",
#				"shelltest3"
#			);

# Grab the user/plan being used:			 
my $user = $OPTS{'user'};
my $plan = $OPTS{'plan'};

# Loop through the plans configured above to determine if this package should have jailshell enabled:i
if (@plans){
	for ( @plans ) {
		if ( $plan eq $_ )  {
			print "Jailshell Package Detected.. \n";
			exec "chsh -s /usr/local/cpanel/bin/jailplans $user" or print STDERR "Couldn't change shell: $!";
			last;
		}
	}
} else {
	print "No data found in /etc/jailshell \n";
}
